apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-preview-secret
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: web-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: fake-preview
  target:
    name: shared-preview-secret
  data:
    - secretKey: message
      remoteRef:
        key: shared-preview-secret
