apiVersion: platform.sonia.so/v1alpha1
kind: PreviewConfig
metadata:
  name: web
spec:
  codeRepository: notniknot/web-apps
  configRepository: notniknot/web-apps-config
  applicationPath: apps/web/base
  previewPathTemplate: previews/pr-{{ pr }}
  image:
    alias: web
    name: ghcr.io/notniknot/web-apps
    tagTemplate: preview-pr-{{ pr }}
    pullSecretName: ghcr-pull-secret
  vcluster:
    hostNamespaceTemplate: web-preview-pr-{{ pr }}
    nameTemplate: web-pr-{{ pr }}
    virtualNamespace: web
  route:
    hostnameTemplate: web-pr-{{ pr }}.sonia-certs.uk
    parentGateway:
      namespace: kgateway-system
      name: north-south
  secrets:
    replicated:
      - name: ghcr-pull-secret
        targetNamespace: web
      - name: shared-preview-secret
        targetNamespace: web
    generated:
      - name: generated-preview-secret
        targetNamespace: web

