apiVersion: v1
kind: ConfigMap
metadata:
  name: preview-params
  labels:
    preview.sonia.so/contract: params
data:
  previewID: local
  configPR: "0"
  hostname: test-case-local.sonia-certs.uk
  applicationName: test-case-apps-preview-local
  imageAllowTags: regexp:^preview-local-.*
  appName: test-case local
  generatedMessage: local-message
