apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: generated-preview-secret
  labels:
    app.kubernetes.io/name: web
    preview.sonia.so/plumbing: generated-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: fake-preview
  target:
    name: generated-preview-secret
  data:
    - secretKey: message
      remoteRef:
        key: generated-preview-secret

