apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-s3-cache
  labels:
    app.kubernetes.io/name: web
    preview.sonia.so/plumbing: s3-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mountpoint-s3

