apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    preview.sonia.so/plumbing: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storage: 1Gi

